// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wrviyqfymzfjubckndnk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indydml5cWZ5bXpmanViY2tuZG5rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MzM5NjMsImV4cCI6MjA2NTUwOTk2M30.94q7qQUQTZtXPwzMEzwlAKDluWLEDGWwuLJ9Z6PH10A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);